[node]
# Dual Stack (sends/receives both IPv4 and IPv6)
listen = "127.0.0.1:9002"
# Virtual MTU of the TAP interface
mtu = 1420
# Name of the interface to create
# tap_name = "laminar0"
# TLS Identity Private Key (Base64 encoded DER)
private_key = "MFECAQEwBQYDK2VwBCIEIJ6FFltScvMPd+fWJOEdrmTAeHdMqn2R4pJpg4wBni71gSEAHnDa5znjtbQRjHrw1dA/sjFULhJY3lWOgsinqOOY/Bs="

# Scaling: Number of parallel streams per connection (0 = Use Datagrams/Unreliable)
streams = 4

# Load Balancing Strategy: water_filling (default), random, sticky
bonding_mode = "water_filling"

# L2 Bridging Config (Optional)
# Uncomment to enable bridging with a physical interface
#[node.bridge]
#name = "br0"
#external_interface = "eth1"

# Network Identity
#mac_address = "02:00:00:00:00:02"
dhcp = false
addresses = [
    { address = "10.100.0.2/24", gateway = "10.100.0.254" },
    { address = "fd00::2/64", gateway = "fd00::ff" },
]
dns = ["8.8.8.8", "1.1.1.1"]

# Lifecycle Hooks
up_script = ""
down_script = ""

[[peers]]
name = "site-a"
public_key = "MCowBQYDK2VwAyEAkUlGvz9hP2ssQ1p9YHc9Tdz9r2aQliWHmkbX++iklRU="
endpoints = ["127.0.0.1:9001", "[::1]:9001"]
